# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 012ea9dbd9977c10ef4cacdffb736931705b9530433144db77a110b95d3d5b3e989fdc546ac2be573e2453d8a5f5581df7f97e2ee178820c71e872d9381db196

test:
  secret_key_base: 4e1e35dc2666f41a0ba5b8c9f2252b0e4d41b6cdb6d65de5ed68cf7216a92d9c055f0c9eaacfb217f6aa5d280ed25d6c29ade5823203a74222b657ee66958b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
